apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: avfc-search
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 2629800000
    segment.bytes: 107374182
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: avfc-search
  labels:
    strimzi.io/cluster: my-connect
spec:
  class: CamelTwittersearchSourceConnector
  tasksMax: 1
  config:
    topics: avfc-search
    # Searches for Aston Ville Football Club
    camel.source.path.keywords: "AVFC OR \"Aston Villa\""
    # Twitter account
    camel.source.endpoint.consumerKey: ${env:TWITTER_CONSUMER_KEY}
    camel.source.endpoint.consumerSecret: ${env:TWITTER_CONSUMER_SECRET}
    camel.source.endpoint.accessToken: ${env:TWITTER_ACCESS_TOKEN}
    camel.source.endpoint.accessTokenSecret: ${env:TWITTER_ACCESS_TOKEN_SECRET}
    # Converting
    camel.source.marshal: json-jackson
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false